-- Correcoes de producao para cadastro/login.
-- Resolve signup 500 causado por trigger fragil e evita auto-promocao de plano pelo client.
-- Rode no SQL Editor do Supabase.

create extension if not exists "uuid-ossp";

alter table public.profiles
  add column if not exists name text default 'Aluno Aprova+',
    add column if not exists email text,
      add column if not exists avatar_url text,
        add column if not exists role text default 'student',
          add column if not exists plano text default 'gratuito',
            add column if not exists status_plano text default 'trial',
              add column if not exists concurso_alvo text,
                add column if not exists data_prova date,
                  add column if not exists nivel text default 'iniciante',
                    add column if not exists horas_semanais integer,
                      add column if not exists dias_disponiveis text[],
                        add column if not exists onboarding_completo boolean default false,
                          add column if not exists trial_inicio timestamptz default now(),
                            add column if not exists plano_ativo boolean default true,
                              add column if not exists plano_expira_em timestamptz default (now() + interval '7 days'),
                                add column if not exists em_teste boolean default true,
                                  add column if not exists vitalicio boolean not null default false,
                                    add column if not exists tour_completo boolean default false,
                                      add column if not exists horas_estudadas integer default 0,
                                        add column if not exists questoes_resolvidas integer default 0,
                                          add column if not exists taxa_acertos integer default 0,
                                            add column if not exists sequencia_dias integer default 0,
                                              add column if not exists taf_nota float default 0,
                                                add column if not exists pontos integer default 0,
                                                  add column if not exists created_at timestamptz default now(),
                                                    add column if not exists updated_at timestamptz default now();

                                                    create table if not exists public.ranking (
                                                      user_id uuid references public.profiles(id) on delete cascade primary key,
                                                        pontos integer default 0,
                                                          posicao integer,
                                                            updated_at timestamptz default now()
                                                            );

                                                            alter table public.profiles
                                                              alter column name set default 'Aluno Aprova+',
                                                                alter column role set default 'student',
                                                                  alter column plano set default 'gratuito',
                                                                    alter column status_plano set default 'trial',
                                                                      alter column plano_ativo set default true,
                                                                        alter column em_teste set default true,
                                                                          alter column vitalicio set default false,
                                                                            alter column onboarding_completo set default false,
                                                                              alter column tour_completo set default false,
                                                                                alter column plano_expira_em set default (now() + interval '7 days');

                                                                                update public.profiles
                                                                                set
                                                                                  name = coalesce(nullif(name, ''), split_part(email, '@', 1), 'Aluno Aprova+'),
                                                                                    role = coalesce(role, 'student'),
                                                                                      plano = coalesce(plano, 'gratuito'),
                                                                                        status_plano = coalesce(status_plano, 'trial'),
                                                                                          plano_ativo = coalesce(plano_ativo, true),
                                                                                            em_teste = coalesce(em_teste, true),
                                                                                              vitalicio = coalesce(vitalicio, false),
                                                                                                trial_inicio = coalesce(trial_inicio, created_at, now()),
                                                                                                  plano_expira_em = case
                                                                                                      when vitalicio = true then null
                                                                                                          else coalesce(plano_expira_em, now() + interval '7 days')
                                                                                                            end,
                                                                                                              updated_at = now();

                                                                                                              create unique index if not exists profiles_email_unique_idx
                                                                                                                on public.profiles(lower(email))
                                                                                                                  where email is not null;

                                                                                                                  create index if not exists profiles_email_idx on public.profiles(email);
                                                                                                                  create index if not exists profiles_plano_ativo_expira_idx on public.profiles(plano_ativo, plano_expira_em);

                                                                                                                  alter table public.profiles enable row level security;

                                                                                                                  drop policy if exists "proprio_perfil" on public.profiles;
                                                                                                                  drop policy if exists "profiles_select_own" on public.profiles;
                                                                                                                  drop policy if exists "profiles_insert_own" on public.profiles;
                                                                                                                  drop policy if exists "profiles_update_own" on public.profiles;
                                                                                                                  drop policy if exists "profiles_delete_own" on public.profiles;

                                                                                                                  create policy "profiles_select_own"
                                                                                                                    on public.profiles
                                                                                                                      for select
                                                                                                                        to authenticated
                                                                                                                          using (auth.uid() = id);

                                                                                                                          create policy "profiles_insert_own"
                                                                                                                            on public.profiles
                                                                                                                              for insert
                                                                                                                                to authenticated
                                                                                                                                  with check (auth.uid() = id);

                                                                                                                                  create policy "profiles_update_own"
                                                                                                                                    on public.profiles
                                                                                                                                      for update
                                                                                                                                        to authenticated
                                                                                                                                          using (auth.uid() = id)
                                                                                                                                            with check (auth.uid() = id);

                                                                                                                                            grant select, insert, update on public.profiles to authenticated;

                                                                                                                                            create or replace function public.protect_profile_admin_fields()
                                                                                                                                            returns trigger
                                                                                                                                            language plpgsql
                                                                                                                                            security definer
                                                                                                                                            set search_path = public
                                                                                                                                            as $$
                                                                                                                                            declare
                                                                                                                                              jwt_role text := coalesce(current_setting('request.jwt.claim.role', true), '');
                                                                                                                                              begin
                                                                                                                                                -- Somente requisicoes REST autenticadas do client sofrem bloqueio.
                                                                                                                                                  -- Triggers internos/auth e service_role continuam podendo criar trial e plano corretamente.
                                                                                                                                                    if jwt_role = 'authenticated' then
                                                                                                                                                        if tg_op = 'INSERT' then
                                                                                                                                                              new.role := 'student';
                                                                                                                                                                    new.plano := coalesce(new.plano, 'gratuito');
                                                                                                                                                                          new.status_plano := coalesce(new.status_plano, 'trial');
                                                                                                                                                                                new.plano_ativo := coalesce(new.plano_ativo, true);
                                                                                                                                                                                      new.plano_expira_em := coalesce(new.plano_expira_em, now() + interval '7 days');
                                                                                                                                                                                            new.em_teste := coalesce(new.em_teste, true);
                                                                                                                                                                                                  new.vitalicio := false;
                                                                                                                                                                                                      elsif tg_op = 'UPDATE' then
                                                                                                                                                                                                            new.role := old.role;
                                                                                                                                                                                                                  new.plano := old.plano;
                                                                                                                                                                                                                        new.status_plano := old.status_plano;
                                                                                                                                                                                                                              new.plano_ativo := old.plano_ativo;
                                                                                                                                                                                                                                    new.plano_expira_em := old.plano_expira_em;
                                                                                                                                                                                                                                          new.em_teste := old.em_teste;
                                                                                                                                                                                                                                                new.vitalicio := old.vitalicio;
                                                                                                                                                                                                                                                    end if;
                                                                                                                                                                                                                                                      end if;

                                                                                                                                                                                                                                                        new.updated_at := now();
                                                                                                                                                                                                                                                          return new;
                                                                                                                                                                                                                                                          end;
                                                                                                                                                                                                                                                          $$;

                                                                                                                                                                                                                                                          drop trigger if exists protect_profile_admin_fields_trigger on public.profiles;
                                                                                                                                                                                                                                                          create trigger protect_profile_admin_fields_trigger
                                                                                                                                                                                                                                                            before insert or update on public.profiles
                                                                                                                                                                                                                                                              for each row
                                                                                                                                                                                                                                                                execute function public.protect_profile_admin_fields();

                                                                                                                                                                                                                                                                create or replace function public.handle_new_user()
                                                                                                                                                                                                                                                                returns trigger
                                                                                                                                                                                                                                                                language plpgsql
                                                                                                                                                                                                                                                                security definer
                                                                                                                                                                                                                                                                set search_path = public
                                                                                                                                                                                                                                                                as $$
                                                                                                                                                                                                                                                                begin
                                                                                                                                                                                                                                                                  insert into public.profiles (
                                                                                                                                                                                                                                                                      id,
                                                                                                                                                                                                                                                                          name,
                                                                                                                                                                                                                                                                              email,
                                                                                                                                                                                                                                                                                  role,
                                                                                                                                                                                                                                                                                      plano,
                                                                                                                                                                                                                                                                                          status_plano,
                                                                                                                                                                                                                                                                                              plano_ativo,
                                                                                                                                                                                                                                                                                                  plano_expira_em,
                                                                                                                                                                                                                                                                                                      em_teste,
                                                                                                                                                                                                                                                                                                          vitalicio,
                                                                                                                                                                                                                                                                                                              trial_inicio,
                                                                                                                                                                                                                                                                                                                  onboarding_completo,
                                                                                                                                                                                                                                                                                                                      tour_completo
                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                          values (
                                                                                                                                                                                                                                                                                                                              new.id,
                                                                                                                                                                                                                                                                                                                                  coalesce(nullif(new.raw_user_meta_data->>'name', ''), split_part(new.email, '@', 1), 'Aluno Aprova+'),
                                                                                                                                                                                                                                                                                                                                      new.email,
                                                                                                                                                                                                                                                                                                                                          'student',
                                                                                                                                                                                                                                                                                                                                              'gratuito',
                                                                                                                                                                                                                                                                                                                                                  'trial',
                                                                                                                                                                                                                                                                                                                                                      true,
                                                                                                                                                                                                                                                                                                                                                          now() + interval '7 days',
                                                                                                                                                                                                                                                                                                                                                              true,
                                                                                                                                                                                                                                                                                                                                                                  false,
                                                                                                                                                                                                                                                                                                                                                                      now(),
                                                                                                                                                                                                                                                                                                                                                                          false,
                                                                                                                                                                                                                                                                                                                                                                              false
                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                  on conflict (id) do update set
                                                                                                                                                                                                                                                                                                                                                                                      email = excluded.email,
                                                                                                                                                                                                                                                                                                                                                                                          name = coalesce(nullif(public.profiles.name, ''), excluded.name),
                                                                                                                                                                                                                                                                                                                                                                                              updated_at = now();

                                                                                                                                                                                                                                                                                                                                                                                                begin
                                                                                                                                                                                                                                                                                                                                                                                                    insert into public.ranking (user_id, pontos)
                                                                                                                                                                                                                                                                                                                                                                                                        values (new.id, 0)
                                                                                                                                                                                                                                                                                                                                                                                                            on conflict (user_id) do nothing;
                                                                                                                                                                                                                                                                                                                                                                                                              exception when others then
                                                                                                                                                                                                                                                                                                                                                                                                                  -- Ranking nao pode quebrar o cadastro.
                                                                                                                                                                                                                                                                                                                                                                                                                      null;
                                                                                                                                                                                                                                                                                                                                                                                                                        end;

                                                                                                                                                                                                                                                                                                                                                                                                                          return new;
                                                                                                                                                                                                                                                                                                                                                                                                                          exception
                                                                                                                                                                                                                                                                                                                                                                                                                            when unique_violation then
                                                                                                                                                                                                                                                                                                                                                                                                                                -- Evita 500 em signup quando existe profile orfao com o mesmo email.
                                                                                                                                                                                                                                                                                                                                                                                                                                    -- O Auth ainda controla email duplicado; aqui apenas nao derrubamos o cadastro
                                                                                                                                                                                                                                                                                                                                                                                                                                        -- por lixo/orfao em profiles. Nao alteramos primary key antiga para nao quebrar FKs.
                                                                                                                                                                                                                                                                                                                                                                                                                                            update public.profiles
                                                                                                                                                                                                                                                                                                                                                                                                                                                set
                                                                                                                                                                                                                                                                                                                                                                                                                                                      email = concat(email, '.orphan.', left(id::text, 8)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            updated_at = now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                where lower(email) = lower(new.email)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      and id <> new.id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          insert into public.profiles (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  role,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        plano,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              status_plano,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    plano_ativo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          plano_expira_em,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                em_teste,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      vitalicio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            trial_inicio,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onboarding_completo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tour_completo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                values (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      new.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            coalesce(nullif(new.raw_user_meta_data->>'name', ''), split_part(new.email, '@', 1), 'Aluno Aprova+'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  new.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'student',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'gratuito',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'trial',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                now() + interval '7 days',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  now(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              false
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      on conflict (id) do update set
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            email = excluded.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name = coalesce(nullif(public.profiles.name, ''), excluded.name),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        updated_at = now();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            begin
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  insert into public.ranking (user_id, pontos)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        values (new.id, 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              on conflict (user_id) do nothing;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  exception when others then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            end;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                end;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $$;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                drop trigger if exists on_auth_user_created on auth.users;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                create trigger on_auth_user_created
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  after insert on auth.users
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for each row execute procedure public.handle_new_user();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    